[package]
name = "csv_to_parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
#avro = "0.2.1"
#csv = "1.3.0"
indicatif = "0.17.8"
parquet = "52.0.0"
polars = { version = "0.40.0", features = ["avro", "csv", "parquet","lazy"] }

